application: ingressier
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/.+
  script: mail.app
  login: admin

- url: /.*
  script: main.app



libraries:
- name: lxml
  version: "2.3"

inbound_services:
- mail