application: sydneyresistancewatch
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/.+
  script: mail.app
  login: admin

- url: /_ah/xmpp/.+
  script: chat.app
  login: admin

- url: /static/style.css
  static_files: static/style.css
  upload: static/style.css

- url: /static
  static_dir: static

- url: /notifications/.*
  script: notification.app

- url: /heatmap.*
  script: heatmap.app

- url: /.*
  script: processor.app
  login: admin

libraries:
- name: lxml
  version: "2.3"

inbound_services:
- mail
- xmpp_message